### ISSUE TITLE
move objc_runtime project wrappers to this project

### ISSUE THREAD

**Issue by bung87** [yglukhov/darwin#17]
am planing move most parts of https://github.com/bung87/objc_runtime/blob/master/src/objc_runtime.nim wrappers to this project, since my project initial purpose is provide `objcr` macro, what do you think?

**Comment by yglukhov** [comment]
That's a cool project, but objc syntax seems out of scope of darwin library, which merely provides the bindings to apple frameworks. Objc itself is being phased out by Swift, so the square brackets will be gone at some point, sigh...

**Comment by bung87** [comment]
I mean the most parts are types and procs wrapped , so I want to move these part this project

**Comment by yglukhov** [comment]
Oh sure, if it's some missing piece of bindings, I'm all for it
