### ISSUE TITLE
Compilation issues on iOS

### ISSUE THREAD

**Issue by kdheepak** [yglukhov/darwin#2]
I get these compilation issues when trying to `import nimx` and compile the nim file to objc and run in XCode.

![](https://files.gitter.im/nim-lang/Nim/9nGm/Screen-Shot-2018-11-05-at-9.07.31-AM.png)

I think it has to do with the fact that nimx imports darwin, which exposes `nspasteboard.nim`. However, that is not available in UIKit, it is a AppKit only construct.

https://github.com/yglukhov/darwin/blob/33daa1a/darwin/app_kit/nspasteboard.nim

 If `darwin` is to be mac/ios bindings, it is possible some changes need to be made in this repository?

**Comment by yglukhov** [comment]
I suppose, that is a bug in nimx. It should not import app_kit related stuff when compiled built for ios.
