### ISSUE TITLE
Example of window

### ISSUE THREAD

**Issue by notchris** [yglukhov/darwin#7]
Can you make an example that opens a new app window for dev

**Comment by kyleparisi** [comment]
I have no idea why I was interested in this but I did some research.  It's pretty messy to make imo.  This [SO reference](https://stackoverflow.com/questions/10289890/how-to-write-ios-app-purely-in-c) is pretty good.  

My efforts were not successful.  There are some methods that are yet to be made, such as [class_addIvar](https://developer.apple.com/documentation/objectivec/1418756-class_addivar).

**Comment by yglukhov** [comment]
I've added a small sample of implementing a class in [timpl_class.nim](https://github.com/yglukhov/darwin/blob/master/tests/timpl_class.nim).

However creating a window is out of scope here, and should be looked up elsewhere.
